/* Generated by Yosys 0.17+33 (git sha1 0b1a1a576, gcc 11.2.0-19ubuntu1 -fPIC -Os) */

/* top =  1  */
/* src = "inverter.v:1.1-8.10" */
module inverter(in, out);
  /* src = "inverter.v:2.14-2.16" */
  input in;
  wire in;
  /* force_downto = 1 */
  /* src = "/yosys/share/gowin/cells_map.v:130.20-130.21" */
  wire in_IBUF_I_O;
  /* src = "inverter.v:3.15-3.18" */
  output out;
  wire out;
  wire out_OBUF_O_I;
  /* keep = 1 */
  IBUF in_IBUF_I (
    .I(in),
    .O(in_IBUF_I_O)
  );
  /* keep = 1 */
  OBUF out_OBUF_O (
    .I(out_OBUF_O_I),
    .O(out)
  );
  /* module_not_derived = 1 */
  /* src = "/yosys/share/gowin/cells_map.v:135.23-136.15" */
  LUT1 out_OBUF_O_I_LUT1_F (
    .F(out_OBUF_O_I),
    .I0(in_IBUF_I_O)
  );
  defparam out_OBUF_O_I_LUT1_F.INIT = 2'h1;
endmodule
