/* Generated by Yosys 0.17+33 (git sha1 0b1a1a576, gcc 11.2.0-19ubuntu1 -fPIC -Os) */

/* top =  1  */
/* src = "inverter.v:1.1-8.10" */
module inverter(in, out);
  wire syn__0_;
  /* force_downto = 32'h00000001 */
  /* src = "/yosys/share/achronix/speedster22i/cells_map.v:42.22-42.23" */
  wire syn__1_;
  /* src = "inverter.v:2.14-2.16" */
  input in;
  wire in;
  /* src = "inverter.v:3.15-3.18" */
  output out;
  wire out;
  /* module_not_derived = 32'h00000001 */
  /* src = "/yosys/share/achronix/speedster22i/cells_map.v:47.42-48.74" */
  LUT4 syn__2_ (
    .din0(syn__1_),
    .din1(1'h0),
    .din2(1'h0),
    .din3(1'h0),
    .dout(syn__0_)
  );
  defparam syn__2_.lut_function = 8'h55;
  /* keep = 32'h00000001 */
  /* module_not_derived = 32'h00000001 */
  /* src = "/yosys/share/achronix/speedster22i/cells_map.v:26.11-26.52" */
  PADIN syn__3_ (
    .padin(in),
    .padout(syn__1_)
  );
  /* keep = 32'h00000001 */
  /* module_not_derived = 32'h00000001 */
  /* src = "/yosys/share/achronix/speedster22i/cells_map.v:30.12-30.64" */
  PADOUT syn__4_ (
    .oe(1'h1),
    .padin(syn__0_),
    .padout(out)
  );
endmodule
