/* Generated by Yosys 0.17+33 (git sha1 0b1a1a576, gcc 11.2.0-19ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "inverter.v:1.1-8.10" *)
module inverter(in, out);
  (* src = "inverter.v:2.14-2.16" *)
  input in;
  wire in;
  wire in_IB_I_O;
  (* src = "inverter.v:3.15-3.18" *)
  output out;
  wire out;
  wire out_OB_O_I;
  (* keep = 32'd1 *)
  IB in_IB_I (
    .I(in),
    .O(in_IB_I_O)
  );
  (* keep = 32'd1 *)
  OB out_OB_O (
    .I(out_OB_O_I),
    .O(out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/yosys/share/nexus/cells_map.v:67.9-67.44" *)
  INV out_OB_O_I_INV_Z (
    .A(in_IB_I_O),
    .Z(out_OB_O_I)
  );
endmodule
