/* Generated by Yosys 0.17+33 (git sha1 0b1a1a576, gcc 11.2.0-19ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "inverter.v:1.1-8.10" *)
module inverter(in, out);
  wire _0_;
  wire _1_;
  (* src = "inverter.v:2.14-2.16" *)
  input in;
  wire in;
  (* src = "inverter.v:3.15-3.18" *)
  output out;
  wire out;
  (* module_not_derived = 32'd1 *)
  (* src = "/yosys/share/sf2/cells_map.v:36.26-36.61" *)
  CFG1 #(
    .INIT(2'h1)
  ) _2_ (
    .A(_0_),
    .Y(_1_)
  );
  (* keep = 32'd1 *)
  INBUF _3_ (
    .PAD(in),
    .Y(_0_)
  );
  (* keep = 32'd1 *)
  OUTBUF _4_ (
    .D(_1_),
    .PAD(out)
  );
endmodule
