/* Generated by Yosys 0.17+33 (git sha1 0b1a1a576, gcc 11.2.0-19ubuntu1 -fPIC -Os) */

module inverter(in, out);
  wire _0_;
  wire _1_;
  input in;
  wire in;
  output out;
  wire out;
  CC_LUT1 #(
    .INIT(2'h1)
  ) _2_ (
    .I0(_1_),
    .O(_0_)
  );
  CC_IBUF _3_ (
    .I(in),
    .Y(_1_)
  );
  CC_OBUF _4_ (
    .A(_0_),
    .O(out)
  );
endmodule
