/* Generated by Yosys 0.17+33 (git sha1 0b1a1a576, gcc 11.2.0-19ubuntu1 -fPIC -Os) */

/* top =  1  */
/* src = "inverter.v:1.1-8.10" */
module inverter(in, out);
  /* src = "inverter.v:2.14-2.16" */
  input in;
  wire in;
  /* src = "inverter.v:3.15-3.18" */
  output out;
  wire out;
  assign out = ~ /* src = "/yosys/share/intel/max10/cells_map.v:44.16-44.21" */ in;
endmodule
